### ISSUE TITLE
One last update

### ISSUE THREAD

**Issue by khanduras** [phryneas/ark_replace_vanilla_engrams#1]
Hey man, 

Really like this tool you made. I see it was last updated sometime in 2017. Now that the mod is finished, at least not worked on by the original creator, I was hoping we could see one last update? I don't really know what's out of date but a final pass would mean a lot.

Cheers!

**Comment by phryneas** [comment]
Question is, what exactly do you need?

I haven't played Ark in almost two years, and don't even have it installed, so some changes might be more complicated than others.

**Comment by khanduras** [comment]
Thanks for the reply,

Honestly I'm not too sure myself. I went through your steps and updated the INI last night but haven't had a chance to play. I've only had my server up since September so can't really comment on what has changed since this was put out.

I'll close this issue for now and if I notice something I'll post in here. I don't think I'd need you to fix it, per se, but I see the csv file I could help update if that works with you.

Cheers!

**Comment by phryneas** [comment]
@khanduras updates are very welcome, just open a Pull Request :)

**Comment by khanduras** [comment]
@phryneas  Should all I need to update is the csv files? I tried to open in Excel but it places each line in the same column rather than tab separated. Is there a better program to edit these in?

**Comment by phryneas** [comment]
If nothing changed with the Ark File format, those csv files should be enough.

I'm not sure what I used back then, but I believe OpenOffice gives you a lot of extra options when importing a csv file.

**Comment by YoYoK3nny** [comment]
If provided with an up-to-date list of engram entries, level requirements and ep costs, would it be possible to get this updated?
Maybe also with support for Platforms Plus?
I've put together an excel workbook with an up-to-date set of engrams and their levels/costs.
(The attached .zip file has the source data with which I made the workbook, if that would work better. They were created using your powershell code)

[ARK Engrams.xlsx](https://github.com/phryneas/ark_replace_vanilla_engrams/files/4364604/ARK.Engrams.xlsx)
[ARK Engrams-Data.zip](https://github.com/phryneas/ark_replace_vanilla_engrams/files/4364605/ARK.Engrams-Data.zip)

Everything is the latest as of the posting of this comment.

**Comment by phryneas** [comment]
@yoyokenny the important data I would need is an updated version of this file:

https://github.com/phryneas/ark_replace_vanilla_engrams/blob/gh-pages/SPlusReplacements.csv

If you can provide me that, I can add it in.
